---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hf-llm.name" . }}-models-cache
  labels:
    {{- include "hf-llm.labels" . | nindent 4 }}
  annotations:
    {{- include "pvc.argocd-syncwave" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.capacity }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  volumeMode: {{ .Values.pvc.volumeMode }}