apiVersion: v1
kind: Service
metadata:
  name: {{ include "hf-llm.name" . }}
  labels:
    {{- include "hf-llm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.containerPort }}
  selector:
    {{- include "hf-llm.selectorLabels" . | nindent 4 }}
